### ISSUE TITLE
Clock doesn't show on all VS Code windows

### ISSUE THREAD

**Issue by fourpastmidnight** [bmealhouse/vscode-shifty#12]
If I have several VS Code windows open, the Shifty clock doesn't show on all of them. In addition, in some cases, but not all the time, in windows where the clock is not displayed, sometimes commands to pause/restart the shift interval fail.

**Comment by bmealhouse** [comment]
Hi @fourpastmidnight, thanks for submitting this issue.

I certainly would like to help figure out what is going on here, but I need more information. Is this a personal or a corporate machine? Windows, Linux, or Mac?

Usually, the remaining time doesn't show up when the user doesn't have write access to the OS temp directory.

**Comment by fourpastmidnight** [comment]
This happens on both personal and corporate machines. In this case, the OS is Windows. I haven’t tried this on a Linux box yet.

I’ll check if there are any Directory permissions issues.

Thanks.

Sent from my Windows 10 phone

**Comment by bmealhouse** [comment]
@fourpastmidnight - Are you still experiencing this issue or was it related to OS temp directory permissions?

**Comment by fourpastmidnight** [comment]
Sorry, I forgot to check the directory permissions. However, sometimes the clock shoes up on some but not all windows, and sometimes only on one. It’s very random.

But given this happens on two different computers (one my personal laptop, the other my corporate domain-joined laptop), I’m thinking its unlikely to be directory permissions.

I’ll try to remember to take a look at those permissions; I’ve been on holiday break.

Sent from my Windows 10 phone

**Comment by bmealhouse** [comment]
No problem. By the way, I just published a new version of shifty with an **enable debugging** command.

Use the command to enable debugging on a VS Code instance that has the issue, then open up the dev tools and use the debug messages to provide more information.

**Comment by bmealhouse** [comment]
@fourpastmidnight - Are you still experiencing this issue?

**Comment by fourpastmidnight** [comment]
Lately, no… our it’s very sporadic. Let’s close this for now. I love this extension. Thanks for making it!

Sent from my Windows 10 phone

**Comment by bmealhouse** [comment]
No problem, I'm glad you're enjoying it! Don't hesitate to reach out if it starts happening more consistently.
