### ISSUE TITLE
Selecting Ignore does not reset the clock

### ISSUE THREAD

**Issue by fourpastmidnight** [bmealhouse/vscode-shifty#13]
Clicking the Ignore button for a theme does not reset the clock. So say you've been away from your computer for a bit and you come back and you see this horrid theme in VS Code and there's 2 minutes left on the shift interval clock. So you dutifully tell Shifty to ignore this theme in the future. Shifty shifts the theme to another, but only 2 minutes remain on the clock.

Instead, Shifty should reset the clock to 30 minutes.

**Comment by bmealhouse** [comment]
Hello, @fourpastmidnight. Thanks again for the feedback.

This is something I've thought about in the past, but I'm torn on this behavior. I will consider your feedback and let you know what I land on.

Are you interested in submitting a PR for this change?

**Comment by fourpastmidnight** [comment]
I was looking through the code, but it wasn't obvious to me, in my quick perusal, how it works. If I have a chance to look at this further, I could give a go at it. Give me a few days, as I’m juggling a few things right now.

Perhaps this behavior could be governed by an additional option that can be set in a user’s configuration? That way, it puts the user more in control of the behavior.

Sent from my Windows 10 phone

**Comment by bmealhouse** [comment]
@fourpastmidnight - I have decided to implement this change. I'm working on some other things right now, but I hope to have this issue resolved in the next couple of weeks.

**Comment by bmealhouse** [comment]
I appreciate you sharing feedback to make shifty better. If you are interested in shifty stickers, send me a DM on Twitter, and I'd be happy to mail some to you.

**Comment by fourpastmidnight** [comment]
I'm glad to hear this. I really enjoy the plug-in! Thanks for your work in making this!!
