### ISSUE TITLE
Feature Request: Shift by filetype

### ISSUE THREAD

**Issue by sahil48** [bmealhouse/vscode-shifty#8]
Shifting theme and font by the file extension of the file opened is a very useful feature I am looking for in visual studio code. There are some syntax highlighting extensions that are readable only in dark mode, and also, when writing markdown files, for me it is preferable to use a variable width font. It would be really great to have this functionality as part of Shifty.

**Comment by bmealhouse** [comment]
Thank you for submitting this feature request @sahil48. Unfortunately, this doesn't match up with the goals I have for shifty (right now). If enough people have a need for this feature, I may reconsider.

I hope you are enjoying shifty! If there is anything else I can do for you, please let me know.
