### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by ben-hapip** [bmealhouse/vscode-shifty#9]
This may seem a bit of a stretch, but is there a way to integrate music with shifty. I was inspired by this when a theme called Hyrule got shifted. Nothing would be more enjoyable than hearing a nostalgic Zelda song while coding my life away 🤪

**Comment by bmealhouse** [comment]
Thanks for submitting this issue @ben-hapip! This is a cool idea, but not one that I will implement in shifty.

You could create your own extension that plays a new track whenever your VS Code color theme changes. Then run your extension alongside shifty to have the experience you're looking for.

🎉
